### ISSUE TITLE
couldn't mount RDWR because of unsupported optional features

### ISSUE THREAD

**Issue by zethis** [toulousain79/MyTomato#2]
When: 
---------
When tried to mount my usb disk on tomato with this commands (in Install_From_Scratch.sh):
```bash
#### Mount /opt
(df -h | grep -q '/tmp/mnt/ENTWARE') && umount /tmp/mnt/ENTWARE
echo "LABEL=ENTWARE /opt ${FILESYSTEM} defaults,data=writeback,noatime,nodiratime 0 0" >/etc/fstab
mount -a
```
Error in dmesg command:
```bash
EXT4-fs (sda1): couldn't mount RDWR because of unsupported optional features (400)
```

How to fix:
--------------
```bash
sudo tune2fs -O ^metadata_csum /dev/xxxx
```

Found it here:
https://unix.stackexchange.com/questions/287159/linux-couldnt-mount-rdwr-because-of-unsupported-optional-features-400

Maybe update the doc ?

Cheers

**Comment by toulousain79** [comment]
Hi Zethis,

Better late than never :-)
Thanks a lot for your feedback.
